baseurl = "http://garaza.io/"
defaultContentLanguage = "si"
theme = "garaza"
author = "Blaz Kostanjsek"
canonifyurls = true
paginate = 10

[taxonomies]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Želiš uresničiti svoje ideje? Postani del Garaže."
  googleAnalytics = "UA-78366821-1"
  dateFormat = "02 Jan 2006, 15:04"

[languages]
[languages.si]
weight = 0
title = "Garaža FRI | Študentski tehnološki pospeševalnik"
[[languages.si.menu.main]]
name = "O Garaži"
weight = 0
identifier = "ogarazi"
url = "/ogarazi/"
[[languages.si.menu.main]]
name = "Programi"
weight = 1
identifier = "programi"
url = "/programi/"
[[languages.si.menu.main]]
name = "Dogodki"
weight = 2
identifier = "event"
url = "/event/"
[[languages.si.menu.main]]
name = "Pridruži Se"
weight = 3
url = "/pridruzise/"
[[languages.si.menu.main]]
name = "FAQ"
weight = 4
url = "/faq/"

[languages.en]
weight = 1
title = "Garaža FRI | Student technology accelerator"
[[languages.en.menu.main]]
name = "About"
weight = 0
identifier = "about"
url = "/about/"
[[languages.en.menu.main]]
name = "Programs"
weight = 1
identifier = "programs"
url = "/programs/"
[[languages.en.menu.main]]
name = "Events"
weight = 2
identifier = "event"
url = "/event/"
[[languages.en.menu.main]]
name = "Join us"
weight = 3
url = "/join/"
[[languages.en.menu.main]]
name = "FAQ"
weight = 4
url = "/faq/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter = "garazaFRI"
  facebook = "*"
  instagram = "garazafri"
  github = "garazaFRI"
  # stackoverflow = "*"
  # linkedin = "*"
